### ISSUE TITLE
感觉还是 homdir 准一点

### ISSUE THREAD

**Issue by popomore** [node-modules/node-homedir#3]
> The value of homedir returned by os.userInfo() is provided by the operating system. This differs from the result of os.homedir(), which queries several environment variables for the home directory before falling back to the operating system response.

**Comment by popomore** [comment]
类似的实现 https://github.com/sindresorhus/os-homedir

**Comment by ngot** [comment]
os-homedir 这个本质上就是 os.homedir. os.homedir会先查询环境变量，再使用操作系统的，在内部好多机器上这样是错的，并不是真的执行用户。
